<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: alex.zie
 * Date: Thu, 10 Nov 2022 23:35:39 +0100
 */

$conf['title'] = 'CEWiki';
$conf['lang'] = 'de-informal';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['defer_js'] = 0;
$conf['proxy']['user'] = 'alex.zie';
$conf['proxy']['pass'] = '<b>ZzdoNDhsM2E=';
$conf['plugin']['indexmenu']['skip_file'] = '/(wiki|sidebar)/';
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,register,themes';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
