<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Wed, 19 Oct 2022 07:40:20 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
