# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 19 Oct 2022 07:40:20 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

alex.zie:$2y$10$OCj4kVMg2fOPsOqvo41LQueEu63fM1SWa33WQk1ihSYpv9Ap61BR6:Alexander Zieschang:Alexander.Zieschang@gmail.com:admin,user
